# Generated by Django 3.1.7 on 2021-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210808_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ادرس الکترونیک'),
        ),
    ]
