# Generated by Django 3.1.7 on 2021-08-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210808_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='work',
        ),
    ]
