# Generated by Django 3.1.7 on 2021-08-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customer_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
