# Generated by Django 3.1.7 on 2021-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkacount',
            name='icons',
            field=models.CharField(choices=[('fa fa-facebook', 'فیس بوک'), ('fa fa-twitter', 'توییتر'), ('fa fa-linkedin', 'لینک دین'), ('fa fa-google-plus', 'گوگل پلاس'), ('fa fa-instagram', 'اینستا گرام'), ('fa fa-whatsapp', 'واتس اپ')], max_length=200, verbose_name='انتخاب شمایل'),
        ),
    ]
