# Generated by Django 3.1.7 on 2021-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=245, null=True, verbose_name='ایمیل'),
        ),
    ]
