# Generated by Django 3.1.7 on 2021-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20210326_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='work',
            field=models.CharField(max_length=50, verbose_name='کار'),
        ),
    ]
