# Generated by Django 3.1.7 on 2021-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20210326_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
