# Generated by Django 3.1.7 on 2021-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210327_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='work',
            field=models.CharField(choices=[('services', 'بازدید کار'), ('waterpump', 'پمپ آب'), ('boilerroom', 'موتور خانه')], default='waterpump', max_length=50, verbose_name='کار'),
        ),
    ]
