# Generated by Django 3.1.7 on 2021-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20210328_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='work',
        ),
    ]
