# Generated by Django 3.1.7 on 2021-03-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20210329_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work_fa', models.CharField(max_length=50, verbose_name='نام کار انگلیسی')),
                ('name_work_en', models.CharField(max_length=50, verbose_name='نام کار فارسی')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='عکس')),
            ],
        ),
        migrations.RemoveField(
            model_name='works',
            name='work',
        ),
        migrations.AddField(
            model_name='works',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.category'),
        ),
    ]
