# Generated by Django 3.1.7 on 2021-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20210329_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pub_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
