# Generated by Django 3.1.7 on 2021-08-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20210420_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='works.category'),
            preserve_default=False,
        ),
    ]
